"""FloodGuard AI — Extended System Router"""
from fastapi import APIRouter
router = APIRouter()

@router.get("/data-modes")
async def get_data_modes():
    """Return all supported data modes and their meanings."""
    return {
        "data_modes": {
            "LIVE": "Real-time data from external providers (requires provider configuration)",
            "HISTORICAL": "Past verified observations from data store",
            "UPLOAD": "User-supplied data (after validation)",
            "DEMO": "Deterministic synthetic data (always labeled, never claimed as live)",
            "SIMULATION": "What-if scenario output (rule-based, not physically calibrated)",
            "REPLAY": "Historical event playback",
        },
        "evidence_states": {
            "OBSERVED": "Directly measured/recorded",
            "REPORTED": "Reported by a person or system (not independently verified)",
            "MODEL_INFERRED": "Computed by a model from other observations",
            "SIMULATED": "Generated by a simulation",
            "UNAVAILABLE": "Source exists but data is not currently available",
            "UNKNOWN": "Evidence state cannot be determined",
        },
        "operational_states": {
            "FRESH": "Data is within acceptable staleness threshold",
            "STALE": "Data is older than staleness threshold",
            "DEGRADED": "Data is available but quality is reduced",
            "UNAVAILABLE": "Data source is not responding",
            "NOT_CONFIGURED": "Provider not configured in this deployment",
            "INSUFFICIENT_DATA": "Not enough data for reliable computation",
        },
    }
